name: translation_string_extractor
version: 0.0.1
description: Extracts .tr and .tr() strings from a project into a JSON file or returns a Map
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  args: ^2.3.0
repository: 
dev_dependencies:
  test: ^1.24.6
  flutter:
    sdk: flutter
  get: ^4.6.5
